### ISSUE TITLE
Excitement

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/jenkins_github_drupal#1]
I just wanted to say that I'm really excited about this project. I've been trying to think of ways to make pull requests more efficient so that we're not all so hesitant to use them and we have more eyes and discussion on the code going into our projects. I think this project will take away the main pain point of having to switch to another branch in order to test it. 

Reviewing the code is pretty painless with GitHub, but getting your local code base to a place where you can test the pull request and then switch back to your previous branch can be daunting, especially if there are database changes to be made/rolled back.

With being able to look at someone's branch already built somewhere, there is a huge potential gain in accepting and using this workflow. So thank you James!

**Comment by q0rban** [comment]
Yay! I'm excited about it too. Thanks, @sirkitree!
