### ISSUE TITLE
Is there any d8 fork  over there?

### ISSUE THREAD

**Issue by calbasi** [Lullabot/jenkins_github_drupal#16]

**Comment by q0rban** [comment]
Hi @calbasi! I can't think of anything off the top of my head in this project that wouldn't work for a D8 project. That said, this project has been deprecated, and all of our work is now being directed towards [Tugboat](https://tugboat.qa). This project is here in the spirit of openness in case anyone wants to do something similar themselves. I hope this helps! :)

**Comment by q0rban** [comment]
@calbasi closing for now, please let me know if you have further questions. :)

**Comment by calbasi** [comment]
Ok, I've read this line at readme file:
"An existing Drupal 7 site with a site alias, and empty prefix line in the database array in settings.php"
and I thought it don't suit new export/import d8 config system, for example... But I have not review your code... In fact, I'm newbie at drupal/git/jenkins world :-)

**Comment by q0rban** [comment]
@calbasi Gotcha! Welcome to Drupal! That's really exciting. You are brave to try to tackle CI on this level so early in your Drupal/git/Jenkins adventure. If it were me, I'd look at [Tugboat](https://tugboat.qa) instead of trying to build this myself with this repo. There's a lot that can go wrong and not a lot of easy solutions to those situations, but a hosted tool can take a lot of the guesswork out.

**Comment by calbasi** [comment]
Hi, @q0rban 
In fact I'm not new at drupal , just to work on a CVS / git basis... All my projects until now are "braves" and unconscious :-) Working at Production :-p But small projects (and their price) has their constrains. 
Well, I read about your suggestion, Tugnoat, but its price is far from my project cash... Even from my freelance scope... I think it could suit an agency, but not a freelance with his own (few) projects... Maybe, as a suggestion, could be a price that suit this profile...
Thanks a lot for your feedback.

**Comment by mettamatt** [comment]
Hey there. We hear you. We're working on ways to be more price competitive for developers and freelancers rather than agencies. Stay tuned, and sign up to the mailing list for more info. Thanks!

**Comment by calbasi** [comment]
Done! Thanks!
