### ISSUE TITLE
sassy jenkins

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/jenkins_github_drupal#3]
One request by our front end team is to make sure that we have the ability to compile sass so that css stays out of the db. ref: https://github.com/Lullabot/sassy-jenkins

**Comment by sirkitree** [comment]
Also, @makangus has something written for the ms... project that might be of use. @makangus can you point us to that code, or paste something here for us?

**Comment by makangus** [comment]
We have something here https://github.com/Lullabot/sassy-jenkins/. It's not perfect but it's something.
