### ISSUE TITLE
license

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/jenkins_github_drupal#4]
Should we have an OSS license on here? If so which one?

**Comment by jjeff** [comment]
MIT is a little more flexible than GPL. What are the other options? Apache?

**Comment by eojthebrave** [comment]
http://choosealicense.com/ is a good resource.

**Comment by sirkitree** [comment]
I think this GPLv2 would do: http://choosealicense.com/licenses/gpl-v2/

**Comment by ericduran** [comment]
MIT :+1:

**Comment by sirkitree** [comment]
Well, that just negated any other votes for MIT :wink:
