### ISSUE TITLE
Better ReadMe

### ISSUE THREAD

**Issue by jjeff** [Lullabot/jenkins_github_drupal#5]
Could we add a paragraph that gives an example use-case for this project in lay-person speak?

The "what does it do" section lists off the mechanics of what happens, but it's not clear WHY someone would want to use this or HOW it makes life easier for Drupal developers.

Perhaps a "Synopsis", "Description", or "Overview" section at the top?

Honestly, I'm not sure what this does myself, but let me make up a paragraph that would say the kind of thing I'm looking for:

> Do you build Drupal sites? Do you use GitHub to manage your code for these projects? Do you use Jenkins to automate continuous integration? Well you should do all of these things! And if you do, then you should also use **Lullabot's Magical Jenkins/Github/Drupal Scripts**™.
> 
> These scripts will {...} so that you can {...}. No more {...}, just install the scripts and {...} will happen automatically every time you {...}.
> 
> Brought to you by your friends at Lullabot!

**Comment by sirkitree** [comment]
Would it be bad to just link to an article? http://www.lullabot.com/blog/article/github-pull-request-builder-drupal

Perhaps a short paragraph **and** a link to an article?

**Comment by sirkitree** [comment]
Created a pull request to start fleshing this out ^
