### ISSUE TITLE
Tear down environment on merge

### ISSUE THREAD

**Issue by juampynr** [Lullabot/jenkins_github_drupal#7]
Maybe I am missing something, but does an environment built for a pull request get teared down if the pull request is merged or closed?

If not, where shall I start looking for to implement it?

**Comment by q0rban** [comment]
I would love for this to be automatic, but it's currently not, which is why they comments have a link to tear down the environment. Our workflow has been:
1. Merge the PR
2. Delete the branch
3. Click the link to tear down the PR environ.

**Comment by juampynr** [comment]
As for the current flow, when you click on the link to tear down, if you are logged in already it does not work since it expects a POST request. I guess that if you are not logged in to Jekins it will work since you are forwarded to the tear down task after logging in, which is POST.

Is there any way for accepting GET request to tear down so people already logged in can do it?

**Comment by q0rban** [comment]
It should work fine, @juampy72, you just have to click the button on the page where it tells you it needs to be a POST.
